name: First Action

on:
  push:
    branches: [ main ]

env:
  IMAGE_NAME: bogdancurenoi/runners:nginxbgd_$(date +%x_%H:%M:%S:%N)

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USER_NAME: ${{env.DOCKERHUB_USER_NAME}}
      DOCKERHUB_PASSWORD: ${{env.DOCKERHUB_PASSWORD}}
    steps:
      - name: Login into Docker
        run: docker login -u $DOCKERHUB_USER_NAME -p $DOCKERHUB_PASSWORD
      - name: Debug docker info
        run: docker info
