name: First Action

on:
  push:
    branches: [ main ]

env:
  IMAGE_NAME: bogdancurenoi/runners:nginxbgd_$(date +%x_%H:%M:%S:%N)
  TEST_VAR: ${{secret.DOCKERHUB_USER_NAME}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Debug env
        run: echo $DOCKERHUB_USER_NAME
      - name: Login into Docker
        run: docker login -u $DOCKERHUB_USER_NAME -p $DOCKERHUB_PASSWORD
      - name: Debug docker info
        run: docker info
