name: First Action

on:
  push:
    branches: [ main ]

env:
  IMAGE_NAME: ""
  DOCK_DATE: ""

jobs:
  job_01:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set current date as env variable
        run: echo "DOCK_DATE=$(date +'%Y-%m-%dT%H-%M-%S')" >> $GITHUB_ENV
      - name: Concatenate envs
        run: echo "IMAGE_NAME=bogdancurenoi/runners:nginxbgd_${{ env.DOCK_DATE }}" >> $GITHUB_ENV
      - name: Store image name
        run: echo $IMAGE_NAME > image_name.txt  
      - name: Give permisions on txt file 
        run: chmod 777 image_name.txt 
      - name: Upload image name as artifact
        uses: actions/upload-artifact@v1
        with:
          name: imgname
          path: image_name.txt
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERHUB_USER_NAME }}
          password: ${{ vars.DOCKERHUB_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: bogdancurenoi/runners:nginxbgd_${{ env.DOCK_DATE }}
  
  job_02:
    name: deploy
    needs: job_01
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Get image name through artifact 
        uses: actions/download-artifact@v1
        with:
          name: imgname
      - name: Store image name for this job 
        run: echo "IMAGE_NAME=$(cat imgname/image_name.txt)" >> $GITHUB_ENV
      - name: Debug variable
        run: echo ${{ env.IMAGE_NAME }}
 