name: First Action

on:
  push:
    branches: [ main ]



jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: bogdancurenoi/runners:nginxbgd_${{github.job_workflow_sha}}
      DOCKERHUB_USER_NAME: bogdancurenoi
    steps:
      - name: Debug env
        run: echo $DOCKERHUB_USER_NAME
      - name: Debug env 2
        run: echo $IMAGE_NAME
      - name: Login into Docker
        run: docker login -u $DOCKERHUB_USER_NAME -p $DOCKERHUB_PASSWORD
      - name: Debug docker info
        run: docker info
